#!/bin/bash
. ~/.sdkman/bin/sdkman-init.sh


if [[ $# -eq 0 ]] ||  [[ "java" == $1 ]]
then
    sdk $( 
        sdk list java | awk -F\| -v OFS='|' \
        '
        header!=1 {
            if ($1 ~ /^-*$/) 
                header=1

            print 
        }  
        
        NF>1 && header==1 {
            if ($1 ~ /^ *$/ ) 
                $1 = previous;
            else 
                previous = $1;

            print
        }
        ' | fzf --height 40% --reverse --header-lines=5 | awk -F\| \
        '{
            if ($5 ~ /^ *$/ ) 
                command = "install";
            else 
                command = "use";

            print command " java " $6
        }'
    )
else

    sdk $(
        sdk list "$1" | awk '
        
        BEGIN {
            FS="  +"
            current_index=0
            separator=0
        }

        $0 ~ /^ *$/ {
            next
        }
        
        $0 ~ /^[>]/ {
            gsub(/[>]/, "<", $0) 
        }
        
        $0 ~ /^[=]*$/ ||  separator < 2 || separator >= 3 {
            if ($0 ~ /^[=]*$/ ) {
                ++separator
                if(separator == 2 || separator == 3) {
                    next
                }
            }

            print
        }

        separator >= 2 && separator < 3 {
            for (i=1; i<= NF; i++) {
                if(!($i ~ "^ *$" || $i == "")){
                    len=split($i, segments, " ")                

                    version=""
                    
                    for (j=len; j>=0; j--) {
                        segment = segments[j]
                        gsub(/[>]/, "<", segment) 
                        version = version " " segment
                    }

                    versions[current_index++]=version
                }
            }
        }

        END {
            asorti(versions, sorted_indexes)
            
            j=length(sorted_indexes)
            
            for(i=1; i<=j; i++) {
                print versions[sorted_indexes[i]]
            }
        }' | fzf --height 40% --reverse --header-lines=6 | awk -v software="$1" \
        '

            NF==2 {
                print "install " software " " $1
            }

            NF>2 {
                print "use " software " " $1
            }
        '
    )
fi

