#!/bin/bash

#TODO Install Dropbox
#TODO Instal google Drive

#colors...
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}Starting a bunch of installations...${NC}"
echo -e "${CYAN}======================================================================${NC}"


echo -e "${CYAN}Password:${NC}"
read -s password


echo -e "${CYAN}Adding PPA repositories${NC}"
echo $password | sudo -S add-apt-repository  ppa:klaus-vormweg/awesome -y
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"

echo -e "${CYAN}Updating apt${NC}"
echo $password | sudo -S apt update
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"

echo -e "${CYAN}Upgrading packages${NC}"
echo $password | sudo -S apt upgrade -y
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"

echo -e "${CYAN}Installing packages...${NC}"
echo $password | sudo -S apt install build-essential\
                                          libbz2-dev \
                                          libffi-dev\
                                          liblzma-dev\
                                          libncurses5-dev\
                                          libncursesw5-dev\
                                          libreadline-dev\
                                          libsqlite3-dev\
                                          libssl-dev\
                                          llvm\
                                          make\
                                          python-openssl\
                                          tk-dev\
                                          xz-utils\
                                          zlib1g-dev\
                                          awesome\
                                          compton\
                                          xscreensaver\
                                          curl\
                                          docker.io\
                                          docker-compose\
                                          git\
                                          gitk\
                                          httpie\
		                     			  meld\
                                          neovim\
					                      alacarte\
                                          tree\
                                          wget\
                                          zsh\
					                      telegram-desktop\
                                          copyq\
                                          -y
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


echo -e "${CYAN}Installing Snaps${NC}"
echo $password | sudo -S snap install code --classic
echo $password | sudo -S snap install slack --classic
echo $password | sudo -S snap install intellij-idea-ultimate --classic --edge
echo $password | sudo -S snap install phpstorm --classic
echo $password | sudo -S snap install pycharm-professional --classic
echo $password | sudo -S snap install datagrip --classic
echo $password | sudo -S snap install webstorm --classic

# echo $password | sudo -S snap install --edge dbeaver-ce
# echo $password | sudo -S snap install insomnia
# echo $password | sudo -S snap install intellij-idea-community --classic
# echo $password | sudo -S snap install pycharm-community --classic
# echo $password | sudo -S snap install android-studio --classic
# echo $password | sudo -S snap install telegram-desktop
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"



# echo -e "${CYAN}Installing Dropbox...${NC}"
# cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
# ~/.dropbox-dist/dropboxd
# echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


echo -e "${CYAN}Intalling Kitty!${NC}"
curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

if [ "$TERM" != "xterm-kitty" ]; then
   echo $password | sudo -S update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /home/lucas.bento/.local/kitty.app/bin 50
fi
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


echo -e "${CYAN}Intalling FZF!${NC}"
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf

if ! hash fzf 2>/dev/null; then
   ~/.fzf/install
fi
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


echo -e "${CYAN}Intalling Oh My Zsh!${NC}"
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"






############################################################################################
# Programming languages
############################################################################################
if [ -e installjava ]; then
    ./installjava
else
    echo -e "${CYAN}Downloading Java instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installjava | bash
fi


if [ -e installpython ]; then
    ./installpython
else
    echo -e "${CYAN}Downloading Python instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installpython | bash
fi


if [ -e installnodejs ]; then
    ./installnodejs
else
    echo -e "${CYAN}Downloading NodeJS instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installnodejs | bash
fi


if [ -e installgolang ]; then
    ./installgolang
else
    echo -e "${CYAN}Downloading Golang instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installgolang | bash
fi


echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}Finished installing everything!!!${NC}"
echo -e "${CYAN}======================================================================${NC}"
