#!/bin/bash

#colors...
CYAN='\033[0;36m'
NC='\033[0m'
echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}Installing Python stuff!!!${NC}"
echo -e "${CYAN}======================================================================${NC}"


if [ -e ~/.pyenv ]; then
    echo -e "${CYAN}Updating PyEnv...${NC}"
    pyenv update
    echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"                    

else
    echo -e "${CYAN}Installing PyEnv...${NC}"
    yes | curl https://pyenv.run | bash


    # Set environment variables to this session
    export PATH="~/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
    echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"                    


    echo -e "${CYAN}Installing Python...${NC}"                    
    # Install Python 3.7.3, because PyEnv doesnt have a 'latest' option
    yes | pyenv install 3.7.3                   

    # Configure Python 3.7.3 globally
    yes | pyenv global 3.7.3
    echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"   

fi


echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}Finished installing Python stuff!!!${NC}"
echo -e "${CYAN}======================================================================${NC}"
