#!/bin/bash

#TODO Install Dropbox
#TODO Instal google Drive

#colors...
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}Starting a bunch of installations...${NC}"
echo -e "${CYAN}======================================================================${NC}"



echo -e "${CYAN}Adding VSCode PPA...${NC}"
sudo apt install software-properties-common apt-transport-https -y
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"

echo -e "${CYAN}Adding DBeaver PPA...${NC}"
yes | sudo add-apt-repository ppa:serge-rider/dbeaver-ce
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"

echo -e "${CYAN}Updating apt${NC}"
sudo apt update
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


echo -e "${CYAN}Upgrading packages${NC}"
sudo apt upgrade -y
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


echo -e "${CYAN}Installing packages...${NC}"
sudo apt install curl\
                 wget\
                 httpie\
                 neovim\
                 git\
                 zsh\
                 docker.io\
		         terminator\
		         copyq\
                 code\
                 dbeaver-ce\
		         -y
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


# Programming languages
if [ -e installjava ]; then
    ./installjava
else
    echo -e "${CYAN}Downloading Java instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installjava | bash
fi


if [ -e installpython ]; then
    ./installpython
else
    echo -e "${CYAN}Downloading Python instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installpython | bash
fi


if [ -e installnodejs ]; then
    ./installnodejs
else
    echo -e "${CYAN}Downloading NodeJS instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installnodejs | bash
fi


if [ -e installgolang ]; then
    ./installgolang
else
    echo -e "${CYAN}Downloading Golang instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installgolang | bash
fi

echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}Finished installing everything!!!${NC}"
echo -e "${CYAN}======================================================================${NC}"