#!/bin/bash

#TODO Install Dropbox
#TODO Instal google Drive

#colors...
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}Starting a bunch of installations...${NC}"
echo -e "${CYAN}======================================================================${NC}"

snap install code --classic
snap install insomnia
snap install --edge dbeaver-ce
sudo snap install intellij-idea-community --classic
sudo snap install pycharm-community --classic
snap install telegram-desktop

echo -e "${CYAN}Updating apt${NC}"
sudo apt update
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"

echo -e "${CYAN}Upgrading packages${NC}"
sudo apt upgrade -y
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"

echo -e "${CYAN}Installing packages...${NC}"
sudo apt install curl\
                 wget\
                 httpie\
                 neovim\
                 git\
                 zsh\
                 docker.io\
		         terminator\
		         copyq\
		         -y
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


# echo -e "${CYAN}Installing Dropbox...${NC}"
# cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
# ~/.dropbox-dist/dropboxd
# echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"

# Programming languages
if [ -e installjava ]; then
    ./installjava
else
    echo -e "${CYAN}Downloading Java instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installjava | bash
fi


if [ -e installpython ]; then
    ./installpython
else
    echo -e "${CYAN}Downloading Python instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installpython | bash
fi


if [ -e installnodejs ]; then
    ./installnodejs
else
    echo -e "${CYAN}Downloading NodeJS instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installnodejs | bash
fi


if [ -e installgolang ]; then
    ./installgolang
else
    echo -e "${CYAN}Downloading Golang instalation script${NC}"
    wget -q -O - https://raw.githubusercontent.com/lucas-bento/dotfiles/instalations/installgolang | bash
fi



echo -e "${CYAN}Installing Oh My Zsh...${NC}"
yes | sh -c "$(wget -O- https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
echo -e "${CYAN}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${NC}"


echo -e "${CYAN}======================================================================${NC}"
echo -e "${CYAN}Finished installing everything!!!${NC}"
echo -e "${CYAN}======================================================================${NC}"
